global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'default'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://185.110.189.68/webhook'  # Update this to your server's webhook URL