name: Deploy Next.js App

on:
  push:
    branches:
      - devops/deploy-ci
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /front/nextjs-app
          git pull origin develop
          npm install
          npm run build
          pm2 restart nextjs-app
